pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                    echo "all OK till this point"
                }
            }
        }
        // stage('Deploy in Staging Environment'){
        //     steps{
        //         build job: 'Deploy_project-stagging-env'

        //     }
            
        // }
        // stage('Deploy to Production'){
        //     steps{
        //         timeout(time:5, unit:'DAYS'){
        //             input message:'Approve PRODUCTION Deployment?'
        //         }
        //         build job: 'Deploy-app-prod-env'
        //     }
        // }
    }
}